version: "2"

services:
  eosd:
    image: eosio/eos-dawn-2.x-fullfix
    command: /opt/eos/bin/start_eosd.sh
    # ports:
      # - 8888:8888
      # - 9876:9876
    # expose:
      # - "8888"
    # volumes:
      # - eosd-data-volume:/opt/eos/bin/data-dir

  walletd:
    image: eosio/eos-dawn-2.x-fullfix
    command: /opt/eos/bin/eos-walletd --http-server-address 0.0.0.0:8888
    # command: /mywork/init.sh
    links:
      - eosd
    volumes:
      - .:/mywork
      # - walletd-data-volume:/opt/eos/bin/data-dir

  facade:
    # build: .
    image: eosio/eos-dawn-2.x-fullfix
    command: /mywork/init.sh 
    links:
      - eosd
      - walletd
    volumes:
      - .:/mywork

# volumes:
  # eosd-data-volume:
  # walletd-data-volume:
